# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MednefitsMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MednefitsMobile
  pod 'GoogleMaps', '~> 2.7.0'
  target 'MednefitsMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  end

  target 'MednefitsMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
